Fix the compilation error on a non-windows environment
Fixed the following compilation error:

```
Assets/UniGLTF_Samples/GltfViewer/OpenFileDialog/OpenFileDialog.cs(10,13): error CS0103: The name 'Debug' does not exist in the current context
```