added DepthFirstScheduler reference to VRM.Sample
fix error

Assets\VRM.Samples\Scripts\VRMRuntimeLoader.cs(166,13): error CS0012: The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'DepthFirstScheduler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.